### ISSUE TITLE
the build scripts don't copy the correct jar file to docker folder

### ISSUE THREAD

**Issue by gangchen03** [ibm-cloud-architecture/microservices-netflix-eureka#1]
It uses command:
cp target/eureka-*.jar docker/app.jar

The build produces jar filename differently, suggest to change it to:
cp build/libs/spring-cloud-eureka-*.jar docker/app.jar

**Comment by osowski** [comment]
Fixed with commit https://github.com/ibm-cloud-architecture/microservices-netflix-eureka/commit/20dd2596856e90a9506f00b0496f3ff2509c2617
