### ISSUE TITLE
file no such file or directory for app.jar file error

### ISSUE THREAD

**Issue by mertmgokce** [ibm-cloud-architecture/microservices-netflix-eureka#13]
I tried to build Dockerfile with 'docker build' command but I take an error like that "lstat app.jar : no such file or directory"
Do you have any idea about that?

**Comment by jesusmah** [comment]
what is the exact command you are issuing? Also, have you previously built the app by using either Maven or Gradle?

**Comment by mertmgokce** [comment]
I solved that issue I applied './build-microservice.sh -m [-d]' it does not produce app.jar. After, I saw similar issue and I applied './build-microservice.sh -d -m' and then it is working.

**Comment by jesusmah** [comment]
Cool. Thanks for the info.
