### ISSUE TITLE
deploy-container-group.sh failed to create container group on Bluemix

### ISSUE THREAD

**Issue by gangchen03** [ibm-cloud-architecture/microservices-netflix-eureka#2]
When executing the script (bluemix cent@us.ibm.com/cloudnative-dev), got following error:
./deploy-container-group.sh
Looking up Bluemix registry images
Registry Image Not Found.  Attempting to push from Local Docker
Error parsing reference: "/chrisking/microservices-refapp-eureka:latest" is not a valid repository/tag
Error parsing reference: "/chrisking/microservices-refapp-eureka:latest" is not a valid repository/tag
Starting Eureka container group
FAILED

{
    "code": "IC5051E", 
    "description": "The image registry.ng.bluemix.net//chrisking/microservices-refapp-eureka:latest could not be retrieved. Verify that the image ID or name is correct.", 
    "incident_id": "1934-1472583121.647-27056889", 
    "name": "ImageNotFound", 
    "rc": "404", 
    "type": "Infrastructure"
}

**Comment by gangchen03** [comment]
the issue seems caused by the line below in file .bluemixrc:
BLUEMIX_REGISTRY_HOST=$(cf ic info | grep Registry | awk '{print $4}')

Should be:
BLUEMIX_REGISTRY_HOST=$(cf ic info | grep Registry | awk '{print $3}')

**Comment by osowski** [comment]
Containers CLI changed, breaking the grep/awk sequence for Registry Host.  Removed that to hardcode with comments instead.
