### ISSUE TITLE
Consolidate build scripts with optional flags

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/microservices-netflix-eureka#4]
Combine `build-gradle.sh` and `build-maven.sh` into a single script that should be the happy path by default, with command flags to alter operation as needed.
- `./build-microservice.sh` - Builds microservice components using `gradlew`
- `./build-microservice.sh -m` - Builds microservice components using `mvn`
- `./build-microservice.sh -d` - Builds microservice and then builds Docker image afterwards _(should be supported with both default and -m build options)_

Let's use Eureka as the first component to consolidate these build options and then we can replicate the same script to other repositories.

**Comment by edwinvandegrift** [comment]
Initial version committed to repo.

**Comment by osowski** [comment]
Completed.
