### ISSUE TITLE
Section Run the Application Component on Bluemix should specify the location of the .bluemixrc file

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/microservices-netflix-eureka#8]
It's under bluemix/.bluemixrc

**Comment by jesusmah** [comment]
README could be updated to mention the location of the .bluemixrc file.
This issue might well happen in other repos since READMEs seems to be all the same...

**Comment by patrocinio** [comment]
Changed to specify the path of the .bluemixrc file
